version: '3.4'

services:
  rectangles.webui:
    image: ${DOCKER_REGISTRY-}rectangleswebui
    build:
      context: .
      dockerfile: UI/Rectangles.WebUI/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1434:1434" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Qwerty@123
